### ISSUE TITLE
The extension page throws some warnings

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb#139]
```PHP
Warning: An unexpected error occurred. Something may be wrong with WordPress.org or this server’s configuration. If you continue to have problems, please try the
support forums. (WordPress could not establish a secure connection to WordPress.org. Please contact your server administrator.) in /homepages/.../wp-admin/includes/plugin-install.php
on line 180
```

**Comment by timnolte** [comment]
I'm not sure but this may be related to the fact that currently the plugin is looking for installer.css and installer.js in an ```assets``` directory within the plugin directory however these files live under ```static``` in the respective ```css``` & ```js``` directories. I went on the server and basically created symbolic links to resolve the issue for the time being.

I also notice that the submission of this plugin looks like a straight commit of the git repository, including SASS source files, instead of a packaged for deployment only commit to the WordPress.org Subversion. The commit to the WordPress.org repository shouldn't include development workflow files. Thanks!

**Comment by pfefferle** [comment]
@timnolte I am not sure which version you use, but the code does not reference any files in the `assets` folder https://github.com/indieweb/wordpress-indieweb/blame/master/includes/class-connekt-plugin-installer.php#L381

@dshanske have you changed the pathes directly in the `Connekt_Plugin_Installer`? If yes, it could break if an other plugin also uses the installer class and "overwrites" the pathes?

**Comment by pfefferle** [comment]
ok, it seems like I assumed: https://github.com/dcooney/wordpress-plugin-installer/blob/master/class-connekt-plugin-installer.php#L360

I think we have to rename the installer!

**Comment by pfefferle** [comment]
@timnolte your problem should be fixed with the next update

**Comment by timnolte** [comment]
@pfefferle thanks, glad you found where it was.
