### ISSUE TITLE
Merge IndieAuth into this plugin 

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#232]
Should we do this?

**Comment by alexture** [comment]
Hi! Just installed this plugin. I didn't see the point of indieAuth and then was told to install it anyway, so I'd 100% merge it for people who don't have all the info they should have :)
(Also, yes, now I see the point of having it.)

**Comment by dshanske** [comment]
@alexture Can I ask about that? Do you feel the page of recommendations is telling you to install it? What can we do to make it clearer that each offers something different?

**Comment by alexture** [comment]
Of course!

This is the text on "Getting started":
**Install and activate the Micropub and IndieAuth plugins.** The Micropub plugin will allow you to publish to your website using Micropub clients and the IndieAuth plugin adds an IndieAuth endpoint to allow authentication through your site, which Micropub requires.
(...)
Browse the Extensions page for a list of other **recommended** IndieWeb plugins that can expand your functionality.

At this point, I read "other recommended" and thought "ok, this is just recommended". Then I installed micropub because at that point I was on the extension page and panicked a bit (I'm really not a big web-tech person!), even though it seems, now that things are working, that I didn't need that either as I only publish from Wordpress. At that point I got the error message telling me to install indieAuth because it was necessary to make other plugins work - but I still haven't figured out whether it's useful for anything else, or if I could remove both at the same time. It feels like Micropub & indieAuth go hand in hand, but maybe there's another reason why they're separate that I just didn't stumble upon in my install.

Hope it helps?

**Comment by dshanske** [comment]
@alexture This has regrettably always been the issue with the Indieweb plugin and the Indieweb plugins for WordPress in general. Micropub requires an IndieAuth endpoint, not necessarily the IndieAuth plugin one. But you can also use the IndieAuth plugin to access the WordPress REST API, or any use it like an OAuth endpoint for any type of client, not just a Micropub one. So, lots of choices there. That's why I opened the issue. Should we just merge everything together? 

Either way, a longstanding problem is how to explain it to people better.

**Comment by gRegorLove** [comment]
I might recommend switching the order of IndieAuth and Micropub in those instructions and maybe a bit less jargon:

"Install the IndieAuth plugin to enable signing in to applications using your domain name and granting permission to publish to your site. Install the Micropub plugin to add support for a variety of Micropub applications that you can use to publish to your site. Note: the Micropub plugin requires IndieAuth."

I know it's possible to set up an IndieAuth endpoint in other ways, but I think this^ is the most common setup people will have.

**Comment by pfefferle** [comment]
My 5 cent to this topic: I think the installer (at least the look and feel) of the IndieWeb plugin is more than a decade old and we do not have to stick with it. I build it, to have a quick (and dirty) way to tell users what to install. There where a lot of improvements done by @dshanske over the years, but the way we present the plugins is still the same and that is the problem in my eyes. We present some plugins with techy names (mostly named by the spec) and the user has to decide/has to know if he needs it or not, but what about a more installer like approach where we ask users what they want to achieve...

Kind of...

What do you want to do?

- [ ] Login to other sites using my website
- [ ] Publish Posts using other toolings
- [ ] Ping other Websites I link to
- [ ] Improve the writing experience in WordPress

The Microformats 2 plugin for example shouldn't be listed at all, but maybe automatically installed if the plugin does not support MF2.

And then install the needed Plugins in afterwards... Maybe with a small hint, what plugin does what...

**Comment by dshanske** [comment]
Closing this as plugin dependencies mean that it can remain a recommendation
