### ISSUE TITLE
Merge Micropub into this plugin 

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#233]
To discuss this question.

**Comment by pfefferle** [comment]
I think it would confuse people even more, if only some plugins are merged and some not. I like the idea to have a wizard, because they may be way more plugins than simply the one we maintain, like the Indie Blocks plugin https://github.com/janboddez/indieblocks by @janboddez

Btw. I tried something similar in 2014 and it decided it was a bad idea https://github.com/indieweb/wordpress-indieweb/tree/15b3210acde096d26f26c4bfc428d6a334bd1157

**Comment by dshanske** [comment]
Abandoning this due no interest.
