### ISSUE TITLE
featured plugins

### ISSUE THREAD

**Issue by pfefferle** [indieweb/wordpress-indieweb#42]
what about a featured plugins approach? i think we should not release unfinished or untested code as part of the indieweb plugin. so what about removing the hcard and rel-me stuff to a featured plugin and merge it into the indieweb plugin core of it is finished and tested?

**Comment by pfefferle** [comment]
@dshanske you mentioned indiemark in one of the other issues... i think this might be another good idea for a feature plugin... giving points for the installed plugins and provide hooks, so that the plugins can also raise points by themselves, and provide a badge or widget that shows there indiemark level...

**Comment by dshanske** [comment]
The user fields were added by @petermolnar in January. I think we're too far to remove it. I certainly agree with iterating further on it, but that can be done in the development version in Github. I think the right thing to do is impose as follows...

1. Immediately address the issues with the currently merged code that affect some individuals.
2. Impose a peer review practice for any new features. Basically, for any new features, we switch back to forking the project instead of committing to the main repository, which several of us are doing. And at least two people have to review any feature and agree before it is merged in. Ideally, I have always wanted more people involved...Right now the active committers to WordPress projects are limited and we need more recruitment.
3. Bug fixes and other similar issues(compatibility testing, typos, etc) would not require the review.

**Comment by dshanske** [comment]
I just turned on the new required review for pull requests option. Therefore, any feature can either be done as a new branch inside the repo or as a forked repo. But it now requires that any pull request have one approved review before merge.

**Comment by dshanske** [comment]
I think this has been addressed by the review option.
