### ISSUE TITLE
Remove some of the plugins in interest of simplicity

### ISSUE THREAD

**Issue by dshanske** [indieweb/wordpress-indieweb#47]
People are overwhelmed by the choice here. What if we whittled down to a core few? We can still recommend the others on the wiki

**Comment by pfefferle** [comment]
I agree! not easy to find the right way between simplicity and complexity...

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/wordpress-indieweb/issues/47" class="u-in-reply-to"></a>I think the biggest hurdle to wider adoption is simply the fact that there are so many individual plugins and this takes up far more mental space for the user than it should. 

So, another option which I'd like to suggest and advocate for is to **bundle all the plugins into one big single plugin** instead of sub-plugins. You could almost sell it as "the part of WordPress core you always wished you had" and now you can with two clicks: download and activate. (That's got to sound good, even to your mom who's still figuring out how to upload her profile picture.)

From the user's standpoint, this wouldn't require much more than some slightly better UI/descriptions. (And I'm more than happy to write them.) This could consist of a single main settings page with on/off toggles for Post Kinds, Syndication Links, Webactions(?), Micropub, Hum, and IndieAuth. A tabbed interface on this same page with tabs primarily for settings/set up and usage description for all of these (except for maybe Webactions?) would complete the cycle.

Most of the sub plugins don't have many (if any) actual settings other than installation/activation right now which is creating the biggest part of the (mostly mental) hurdle for every day users. I think the average WordPress user probably wouldn't know that they had Webmentions, Semantic Linkbacks, or Webmentions for Threaded Comments installed because they "just work", require no configuration, but are far prettier than any of their predecessors. Why make them carry the mental overhead of what they are and what they do aside from a few subtle lines that they exist?  In fact, treating them as if they should have been in  WordPress core all along may actually make it more likely to happen.

Additionally things like Micropub which would only have an on/off toggle wouldn't be noticed or used by many unless they had interest in alternate posting interfaces. (And based on the popularity and growth in Twitter interfaces/apps a few years ago, I'm surprised WordPress didn't do this, though perhaps it's part of the reason they're adding a more robust API over the past few years?)

It also means having slightly better or more intuitive explanations of what the individual pieces are (mostly Syndication Links and Post Kinds) near their on/off toggles to better explain what is being activated. Much of this can be taken from the current interface or from the WordPress wiki pages, or added on the individual tabs for the settings for these portions.

I would suggest that doing this would not only make it easier on end users who then wouldn't have to spend the mental space and capacity to keep track of what 10 individual plugins are doing (in addition to the space these take up on the plugin admin page and the fact that, once activated, they disappear from the IndieWeb plugin's list of plugins), but that it would actually dramatically increase the uptake of the single big plugin and its functionality and simultaneously the use of the all the sub plugins individually.

I'd argue that bigger plugins like Yoast SEO or something like PressForward have huge numbers of options and settings and could have been done as separate sub-plugins (the way IndieWeb Plugin is now), but that their value proposition is such that it's well worth spending the handful of minutes reading through the interface to know what the options are, what they mean, and using them to their fullest advantage. I think that Indieweb (and the suite of tools offered on WordPress) is at this tipping point in terms of offering must-have functionality for the future web and that having a simpler integrated set up would help to push it over the edge to broader adoption. (Certainly simpler than the old WP-Social, which users have indicated that they thought was far simpler than Indieweb plugin, though Social actually required more set up.) Additionally all of the seemingly dense text in the "getting started" page could be moved into smaller bit-sized chunks relating to individual portions on a tabbed-interface, for example.

I come to this in part after having spent part of the weekend revamping a bit of the IndieWeb.org documentation on getting started with WordPress and setting up Bridgy with WordPress.  A lot of the description is "get this plugin, install, and activate" which takes up a big piece of mental space for the user as well--particularly for the Gen2, 3, 4 users who want a plug and play experience. Far better would be to install one plugin and then modify these handful of settings.

If this is done, then the only remaining (small) hurdle is making sure that the underpinning rel-me data input required of the user is done in a more explicit manner, because this seems to be the lynch-pin holding a lot of it together and making it work.  As a result, I'd recommend unbundling the reliance on the User Profile page and put all the rel-me URL fields on their own page in the settings interface for such a single plugin (with all important links just underneath them to encourage users to visit, for example, Twitter's edit profile page to include their website URL in either the website field or in the bio field to enable the bi-directional rel-me.)

Finally a "Tools" tab in the settings page could provide pointer links to additional things like the H-Card Widget or the IndieWeb-PressThis bookmarklets.

When all of this is done, it could also be a simple manner of adding another settings tab to the interface to set up Bridgy with one button links from the plugin to the set up pages for each of the main backfeed services there. Bridgy then automatically checks for the webmention endpoint and checks for rel-me to do it's work, so that part is already automated and relatively user friendly too.

The one caveat I can imagine is that making it all into one big plugin potentially means some small added overhead in development with maintaining some of them as stand alone pieces. I'd recommend keeping them as standalone objects as I honestly believe that pieces like webmentions and micropub are so fundamental to the web, that they should be part of WordPress core and maintaining them separately could help speed this along.

**Comment by dshanske** [comment]
There wouldn't be overhead. We can still develop them independently. I know pfefferle has been playing with composer. We could build the components.

**Comment by pfefferle** [comment]
@chrisaldrich thanks for the detailed feedback and for taking the time to write it down. I totally understand every single point you mentioned above, but I am not sure how to handle the problem. I started working on the plugins with one simple rule in mind: "eat your own dogfood". That's why they are very simple and that's why there are a lot of them. I see no advantage for me personally, to have a single plugin to implement the whole IndieWeb stack. I have very little spare time to work on all of these plugins, so I focus on the ones, I really use.

But as I said, I love the idea and totally understand all of the points from a user perspective. I am open for suggestions and will provide as much feedback as I can... but I can't/won't be very active, except someone pays me for working full time on IndieWordPress stuff ;)

**Comment by chrisaldrich** [comment]
<a href="https://github.com/indieweb/wordpress-indieweb/issues/47#issuecomment-276394643" class="u-in-reply-to"></a>@pfefferle And there in a small nutshell is both the power and the drawback of part of the movement, particularly on a platform that powers 25% of the internet. I'm in the same boat with you (though my coding skills are far behind), but I thought I'd write down the blue sky idea as a potential target for the future. Perhaps we should follow Manton Reece's lead and create a Kickstarter campaign to fund such a thing? (_Said in half-jest/half-seriousness_).

I suppose the thing to continue focusing on is steady improvement of what already exists. Eventually a group of developers will join us all and separately or together we'll have the free time to bundle it all up the way we all imagine it sould be done on a salaried basis.

If I (or we, speaking on behalf of the rest of the community) don't say it often enough, **THANK YOU** again @pfefferle and @dshanske for your heroic efforts on behalf of the IndieWeb within WordPress.

**Comment by voxpelli** [comment]
I think it would make sense to not do a one-size-fits-all plugin.

What exists now works for power users, is very customizable and can be extended and configured to try out many new interesting things, which enables good dogfooding of new approaches.

It's however hard to get started with. So having a single "IndieWeb Lite"/"IndieWeb Starter" module that contains an easy setup would be easier for new users.

One doesn't exclude the other, they both could ideally feed one another with code and ideas, but ultimately they would serve different purposes.

**Comment by miklb** [comment]
in e9e6cfb55030a451fa0f2301e6f86d69157b4eb2 the list was simplified. In IRC discussion was mentioned only plugins in the wp.org repo are listed, but I'm still seeing the IW Press This plugin in a GitHub repo.

Semi-related, the micropub plugin is set a `required` in `register_required_plugins()` but I believe is meant as a suggested, not required.

**Comment by dshanske** [comment]
Forgot about Press This

**Comment by miklb** [comment]
I mostly ask because I am evaluating that alternate plugin installer class, and it currently doesn't support GitHub repos.

**Comment by dshanske** [comment]
I think even if we have to propose publishing the Indieweb Press This mods, removing, or merging them, still worth exploring

**Comment by dshanske** [comment]
Addressed in PR #52
